### ISSUE TITLE
ORCA - Do not let users click through safe links & Enable Safe Links Synchronous URL detonation

### ISSUE THREAD

**Issue by debcampbellcoop** [cammurray/orca#152]
Problem 1:
Selected Domains Policy  DoNotAllowClickThrough - no value - I cannot change this value since the property has been deprecated by Microsoft - I want to change it to False - it's saying Not Recommended -15

Problem 2:
Enable Safe Links Synchronous URL detonation - Enabled False - Not Recommended  -10 - I don't know how to change this?  what does "All" refer to?

**Comment by laklug** [comment]
Yes, I agree. In addition to Problem 1 it's the same with DoNotTrackUserClicks. It's now "TrackClicks".

![TrackClicks](https://user-images.githubusercontent.com/99720138/169000873-c6c44507-8604-4c49-86d7-f92e59014ace.jpg)

**Comment by debcampbellcoop** [comment]
Hi there, can anyone from GitHub respond to this?  there are other similar elements with this issue...we seem to get new ones each week that we run ORCA

**Comment by snehakishore21** [comment]
@debcampbellcoop,  there are some changes in the PowerShell cmdlets of the MDO policies. The parameters that we were using does not exist now. The parameters are renamed, so we need to update it in our tool. These 2 parameters are affected because of that:
1.	DoNotTrackUserClicks
2.	DoNotAllowClickThrough
 
@debcampbellcoop 
First issue will be resolved once we update the above parameter names. We will update it and it will be fixed in the next release.
And if you want to update the property, for that you can use the following cmdlet:
 
![image](https://user-images.githubusercontent.com/69503744/170663446-e99609bc-cde9-42f7-bb80-13930dfa99e7.png)


For the second issue, that seems to be a bug in the tool. You don’t need to change anything from your side.
‘All’ here signifies that all the policies are disabled and this row is added by default in the check(the cmdlet is not checking for correct status of the policies because of some recent changes in the product PowerShell cmdlet). We will update this(to check for correct status) as per current cmdlet in the next release.

@laklug your problem is also because of changes in the parameter name. This will also be resolved in the next release.

**Comment by debcampbellcoop** [comment]
Thanks snehakishore21, yes, I was able to set -AllowClickThrough to $false so that part is good.

As for the other elements that need to be fixed from your end, when is the next release?

I appreciate you responding to my query :)

**Comment by snehakishore21** [comment]
Engineering team is working on that. We will have our next release by the end of this month or earlier.

**Comment by snehakishore21** [comment]
@debcampbellcoop we have released new version with the required changes. You can test once and let us know if you are still experiencing any issues.

**Comment by debcampbellcoop** [comment]
Hi there, I just ran ORCA and it still looks the same to me.  Thoughts??

***@***.***


Deb Campbell | Technical Analyst
Enterprise Collaboration Services | The Co-operators Group Limited
130 Macdonell Street, Guelph, ON, N1H 6P8
Tel: 519-824-4400 |  Toll Free: 1-800-265-2662 Ext. 302157

**Comment by snehakishore21** [comment]
@debcampbellcoop  Have you used ORCA Preview version 2.1?
https://www.powershellgallery.com/packages/ORCAPreview/2.1

**Comment by cammurray** [comment]
Closing off as no response from author that they're using latest module
