### ISSUE TITLE
Out-File could not find a part of the path

### ISSUE THREAD

**Issue by lloydms** [cammurray/orca#170]
I have ran the ORCA report command. The report runs without error, but  when running the output, the following error is generated

<img width="701" alt="image" src="https://user-images.githubusercontent.com/13806488/228593497-d0195d59-b15a-4bbf-82db-a9216ca58240.png">

I have tried changing the OutputDir variable to a static value, which hasn't helped. Nothing else seems to be causing the issue. I am running PS on a Mac, if that matters.

Thanks,

Mike

**Comment by EarlCrane** [comment]
Having this same issue.

**Comment by lloydms** [comment]
> Having this same issue. MacOS with homebrew. I notice the script creates a directory called "/Microsoft/ORCA" rather than creating a directory "Microsoft" with child "ORCA" Still troubleshooting to see if I can manually redirect.

So, I ended up just running it on Windows, as forcing the path redirect wasn't working for me. Perhaps Microsoft will eventually change the script to account for all OSes.

**Comment by EarlCrane** [comment]
@lloydms the ORCA.psm1 invokes $IsMac but it should be $IsMacOS

I'm trying to edit to fix the path issue but I don't know powershell well

**Comment by EarlCrane** [comment]
@lloydms I created two PRs to fix the $IsMacOS and the corresponding path issues. I used new-item instead of mkdir to create the folder correctly.

**Comment by RStadlmair** [comment]
macOS here, same issue, would reaally appreciate the PR´s to make it work iin macOS.

**Comment by cammurray** [comment]
Hey all, first off thanks @EarlCrane for the PR - i've reviewed it but unfortunately it was changing more than I was comfortable with, specifically using the current path instead of the special paths, so I took your changes and made #174 

Forgive the delays here, I was on paternity leave, technically as well there's a team that maintains this but they might be under load so i'll help out here again and get rid of some of this backlog.
