### ISSUE TITLE
ORCA will not connect when used to check an Exchange Online Hybrid instance

### ISSUE THREAD

**Issue by sbrackeen** [cammurray/orca#2]
ORCA fails to connect in Exchange Online Powershell when used in an Exchange Online Hybrid setup,

```
PS C:\Users\sean.brackeen> Get-OrcaReport
11/18/2019 14:59:08 Performing ORCA Version check...
11/18/2019 14:59:10 Connecting to Exchange Online..
ORCA was unable to connect to Exchange Online.
At C:\Program Files\WindowsPowerShell\Modules\ORCA\1.2.1\ORCA.psm1:1343 char:9
+         Throw "ORCA was unable to connect to Exchange Online."
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (ORCA was unable...xchange Online.:String) [], RuntimeException
    + FullyQualifiedErrorId : ORCA was unable to connect to Exchange Online.

```

Looking at the other issue in this tracker it appears that it depends on Get-Mailbox to see if a connection is already available, which is not an available command once connected to Exchange Online in Hybrid mode, since Hybrid accounts do not always contain mailboxes.

I'm not sure if this is a WontFix since you may not be interested in fixing this for Hybrid deployments, but using EOP and ATP is valid for Exchange Hybrid, and I would be interested in using this script.

**Comment by cammurray** [comment]
Hi @sbrackeen 

There's no issues with being in a Hybrid, it's just that you need to ensure you're connected to the right Exchange environment. E.g instead of loading the Exchange Management Shell, you should load the Exchange Online PowerShell Module (http://aka.ms/exopsmodule) **OR**, just use a standard PowerShell window that has the new Exchange preview module installed (https://www.powershellgallery.com/packages/ExchangeOnlineManagement)

Could you just verify for me the above?

Saying that though, we should probably change from 'Get-Mailbox' to a command that's only specifically available in Exchange Online. In that way, we can ensure that the right environment is connected to.
