### ISSUE TITLE
The output for quarantine notification check is confusing on the HTML page

### ISSUE THREAD

**Issue by damozes1** [cammurray/orca#221]
[orca](https://github.com/cammurray/orca/tree/a4f82885018de072b9ca43ba01c5635f3bd03da6)/[Checks](https://github.com/cammurray/orca/tree/a4f82885018de072b9ca43ba01c5635f3bd03da6/Checks)
/check-ORCA107.ps1 

The checks called spam notifications but the Quarantine notification feature moved from Spam policy to Quarantine policy. It is controlled by the Quarantine policies for each action not just for Spam policy but also for other policy types (Phish, Malware, etc.) where the action is set to Quarantine. for each Quarantine action the assigned Quarantine policy will determine if the notification email will include the detection or not. 
Frequency is a global settings now for Quarantine notification and the new options are within 4 hour, Daily, Weekly.

We should update the output of the check in HTML to cover the recommended quarantine policy settings for each Quarantine action vs Standard/Strict. Eg HCP recommended to Quarantine and the Quarantine policy assigned for this action should not enable to be included in the notification digest email.  
Also settle on a new recommended frequency eg. "Daily"  which can be checked on the global setting.
![image](https://github.com/cammurray/orca/assets/45426291/25c581d6-023e-49a1-8dc7-35d67d47ba92)

Also the links to documentation should be updated in the HTML report for this check

**Comment by cammurray** [comment]
@damozes1 Moved to using the quarantine policy as the object being checked, rather than the individual policies.

We now check to see if the quarantine policy is in use as a spam, HC spam, or bulk tag in a spam policy, and if it is we check ESNEnabled property. If it's in use and ESNEnabled = False, it's a fail, if ESNEnabled = true, it's a pass.

If the quarantine policy is not in use as a spam, HC spam, or bulk tag, and ESNEnabled is false, we will raise it as informational only - similar experience as what we do with any other disabled policy.
