### ISSUE TITLE
Check output says no Safe Links/Safe Attachment policy applies to domains which are in scope of active Safe Links/Safe Attachment policies

### ISSUE THREAD

**Issue by damozes1** [cammurray/orca#224]
Check output incorrectly say no Safe Links/Safe attachment policy applies to domains which are in scope of active Safe Links/Safe Attachment policies
check-ORCA227.ps1
check-ORCA226.ps1

**Comment by cammurray** [comment]
This is not a bug but a shortfall in the design.

It's just that the way that this check is coded at the moment is that it checks for domain inclusion, but ignores rules applying the policy which have exceptions. It's been this way since ORCA was born, because doing exception level checking is quite complex.

I think we will do this, and change this, but as a new bit of work and not as a bug. Tracking this in #238
