### ISSUE TITLE
First contact Safety tip check should also consider when ETR used to enable it

### ISSUE THREAD

**Issue by damozes1** [cammurray/orca#225]
although it is not recommended anymore ETR still can be used to enable first contact safety tips. 
check-ORCA241.ps1 should consider and check the usage of ETR for enabling the feature not just the Anti-Phish policy option
https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/anti-phishing-policies-about?view=o365-worldwide#first-contact-safety-tip

**Comment by cammurray** [comment]
Agreed, but bumping to vnext.

**Comment by cammurray** [comment]
@damozes1 i've implemented this but;

- It's too hard to determine exceptions/conditions, so we're only considering transport rules with no exceptions & conditions
- In the instance we find a TR rule setting the header that has no conditions/exceptions, any policy that doesnt have FC enabled on it will be considered informational, rather than fail - pointing to the TR rule.
