### ISSUE TITLE
Error with Get-ProtectionAlert

### ISSUE THREAD

**Issue by brianberryNZ** [cammurray/orca#247]
When I run Get-ORCAReport, I get an error related to Get-ProtectionAlert:
_"Get-ProtectionAlert: The term 'Get-ProtectionAlert' is not recognized as a name of a cmdlet, function, script file, or executable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again."_
I find that I need to first run _Connect-IPPSSession -UserPrincipalName User@someplace.some_ before I can use _Get-ProtectionAlert_ interactively, otherwise I get the same error.
I'm running ExchangeOnlineManagement 3.2.0 and running the report from PowerShell 7.3.5.

**Comment by cammurray** [comment]
Hi @brianberryNZ 

That's unusual, because we run Connect-IPPSSession as part of Get-ORCAReport.

Can you confirm some things for me;

- Are you running Get-ORCAReport from a fresh new powershell window? (Just seeing if there's a stale connection)
- When you run Get-ORCAReport, are you asked to login twice, or just once? (One should be for Exchange Online and the second for SCC)

**Comment by brianberryNZ** [comment]
Hi @cammurray,
I have tested again from a VM so I can isolate other logins. I do get 2 login prompts, and if I log in to both, the report runs fine.

I think I must have missed the second login prompt, or maybe it used another credential. Most likely I missed it because on my main machine, it pops up in the background for some reason.
Some feedback on the tool and report. We use it to review our configs every 3 months. It provides a great way to keep on top of config drift changes made by some team members, and helps us stay on top of the latest recommendations. THANKS!
