### ISSUE TITLE
Tenant Settings Unified Audit Log returning wrong value

### ISSUE THREAD

**Issue by sfothersgill** [cammurray/orca#249]
Using version 2.5, the ORCA Report shows improvement for the Tenant Settings - Enable the Unified Audit Log. When checking our tenancy, the EXO PS cmdlet "Get-AdminAuditLogConfig | Select UnifiedAuditLogIngestionEnabled" returns True. I think the ORCA script is running the cmdlet from the Security & Compliance module, which always returns a value of false. Refer to the MS article https://learn.microsoft.com/en-us/microsoft-365/compliance/audit-log-enable-disable?view=o365-worldwide#verify-the-auditing-status-for-your-organization

**Comment by cammurray** [comment]
Hey @sfothersgill 

Thanks for reporting this, that's not deliberate but as a result of us now connecting to the Security & Compliance Module. It appears the command exists in both and the SCC is winning as the connection is made second.

In the interim, can just run with the -NoSCC flag and it won't connect.

Will get this one fixed though.

**Comment by cammurray** [comment]
On consideration we are going to deprecate this check.
- It's more important that we check for alert policies (which is why we need to connect to SCC)
- It's very unlikely now to find instances where UAL is disabled
- Even in instances of UAL being disabled, I find it hard to see the connection between the UAL and MDO
