### ISSUE TITLE
Running without ATP

### ISSUE THREAD

**Issue by sean-anr** [cammurray/orca#3]
I realize that this is meant to be run with ATP, however, it would be nice to be able to run it without ATP as a selling tool to show just how many security issues they have.

**Comment by cammurray** [comment]
thanks @sean-anr for the feedback,

it's primarily designed to review configuration that will impact Office 365 ATP, however, there are some findings that relate to EOP by itself.

When running in an environment that doesn't have ATP, there will probably be errors presented when attempting to get the configuration. Other than that, it should theoretically still work.

**Comment by Absoblogginlutely** [comment]
As an alternative and to provide cleaner output, would it be better to check if ATP policies are available and skip it not (or provide some kind of "you do not have ATP in your licence" error message)
The script output is ugly otherwise (although most users are only going to be concerned with the html file) as shown below.
![Screenshot - 20200214-114724](https://user-images.githubusercontent.com/21364480/74550779-f159dc00-4f1f-11ea-828b-c1e4d2e56d8b.png)

**Comment by cammurray** [comment]
Thanks for the feedback @Absoblogginlutely - the intent for Office 365 ATP Recommended Configuration Analyzer (ORCA) was to review ATP configuration, but I can certainly see that there's value with the base non-ATP specific EOP configuration that it reviews, too.

I can look at potentially ignoring the ATP checks (including suppressing the errors) but placing a banner on the report to say that ATP checks were skipped.

**Comment by cammurray** [comment]
@Absoblogginlutely @sean-anr 

This is handled in the next version by suppressing the errors and showing 'graceful' messages:

**Running the report**

![image](https://user-images.githubusercontent.com/26195772/75123210-9a12f300-56f9-11ea-9935-aec6ffd7115e.png)

**Viewing the report**

![image](https://user-images.githubusercontent.com/26195772/75123215-a5661e80-56f9-11ea-8547-f54900567534.png)

**Comment by cammurray** [comment]
Code is checked in and will be in 1.4 release.
