### ISSUE TITLE
Deprecation of ASF control

### ISSUE THREAD

**Issue by helmutacp** [cammurray/orca#317]
I googled the deprecation of ASF controls. Didn't find any real source.
Can you please provide the source of this information?

**Comment by cammurray** [comment]
@helmutacp, plans have been in the works and out of the works for some time. At the moment there's no plans - but the recommendation still stands that they are not recommended due to FP/FN risks. The wording has been changed in a recent update to align to the real reason, but the code has yet to been pushed out due to a signing issue we have at the moment. For ref: https://github.com/cammurray/orca/pull/314/commits/7071a54f9010528995b7c8caf7c07f56b83f3106

@nithinnara fyi

**Comment by helmutacp** [comment]
Thank you for the explanation!
