### ISSUE TITLE
Need for other output types i.e. json

### ISSUE THREAD

**Issue by davidcrossland** [cammurray/orca#57]
Hi (caveat i know virtually nothing about exchange), im working for an organisation where we want to schedule a run of the ORCA report inspect the results and potentially notify individuals of configuration drift that may make their platform insecure.  At present im thinking of leveraging this module for this task.  It would be very useful to have a json representation of the report to accomplish this. Is this something you could consider adding?  Otherwise i will have to fork and maintain a version of this code that would allow for this and would mean that i somehow have to keep up to date with enhancements that you make to this library which is not ideal.

**Comment by cammurray** [comment]
Hi @davidcrossland 

We plan on having other outputs in ORCA as part of #9 . The ground work for that will be to make the output modular, and then create an output module for storing in Azure table. Once that work is complete it will be simple to make other outputs too, such as json.

So i'd expect us to have this in the next couple of weeks.

**Comment by davidcrossland** [comment]
Excellent, thanks for letting me know.  This will be very useful for our project :D

**Comment by cammurray** [comment]
Hi @davidcrossland 

We've checked in changes which can be seen in the preview module in the gallery, but should be in the prod module in the next week or two.

Output is modular, and two supported modules at the moment are HTML and JSON.

In the preview module if you want to get a JSON output, instead of running "Get-ORCAReport" run "Invoke-ORCA -Output JSON". This will output a JSON file. We will soon make a module to output JSON in the returned value of the command (instead of file) soon.

If you want additional output types, feel free to fork, create an output module (look at the files output-html.ps1 and output-json.ps1 for examples), and then perform a pull request back in. We will review that and then check it in if it's fine.

Cheers.
