### ISSUE TITLE
Whitelisted Domains - Disabled Transport Rule

### ISSUE THREAD

**Issue by ThijsLecomte** [cammurray/orca#7]
I just noticted 'Remove whitelisting on domains' portion of ORCA through Transport rules also fails when the transport rule is disabled.

I guess this shouldn't really be the case? As the transport rule isn't enabled, this shouldn't have effect on the score.

**Comment by cammurray** [comment]
thanks @ThijsLecomte 

We don't 'score' the results as such, but yes, aware that some disabled components can cause the result to say improvement is required. There are two thoughts around this; 

- The first is that the configuration is not enabled (and therefor shouldn't impact you).  Which is very valid.
- The second is that though the configuration is disabled, we still want to make you aware that configuration is potentially harmful in case you decide to re-enable it.

So saying that, I think what we may want to do is introduce "Informational" results in to the findings, and probably raise these ones as informational rather than improvement.

**Comment by cammurray** [comment]
Hi @ThijsLecomte 
In the 1.6 release for next week we will be introducing 'informational' classification and bad transport rules that are in a disabled state will be flagged as so.

**Comment by cammurray** [comment]
Code checked in to #56 for 1.7 release, represented now by "Informational" classification as seen below:

![image](https://user-images.githubusercontent.com/26195772/80670460-4acab380-8aea-11ea-9471-cea1b21e3b01.png)
