### ISSUE TITLE
Basic authentication required

### ISSUE THREAD

**Issue by danielmaddern** [cammurray/orca#75]
Hi, 
Is it possible to use the ORCA report tool without enabling basic auth?
Happy to assist in making this happen if you can let me know where I should start.

Thanks,
Daniel

```PS C:\Users\Username> Get-ORCAReport
05/19/2020 12:19:49 Performing ORCA Version check...
05/19/2020 12:21:49 Connecting to Exchange Online..
New-ExoPSSession : Connecting to remote server outlook.office365.com failed with the following error message : The
WinRM client cannot process the request. Basic authentication is currently disabled in the client configuration.
Change the client configuration and try the request again. For more information, see the about_Remote_Troubleshooting
Help topic.
At C:\Users\Username\AppData\Local\Apps\2.0\LR9KCPZ3.8JK\PLATQYJN.38Y\micr..tion_1f16bd4ec4c2bb19_0010.0000_673f37
c317fb5976\CreateExoPSSession.ps1:302 char:30
+ ... PSSession = New-ExoPSSession -UserPrincipalName $UserPrincipalName.Va ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [New-ExoPSSession], PSRemotingTransportException
    + FullyQualifiedErrorId : System.Management.Automation.Remoting.PSRemotingDataStructureException,Microsoft.Exchang
   e.Management.ExoPowershellSnapin.NewExoPSSession```

**Comment by cammurray** [comment]
Hi @danielmaddern 

This is not an issue with ORCA it's an issue with Exchange Online and its reliance on Remote PowerShell. All methods for connecting using PowerShell (including the REST enabled module - because REST still performs a legacy connection for access to the legacy commands) use remote PowerShell to connect to Exchange Online.

If you are using the ExchangeOnlineManagement module (the new REST enabled module), this  **uses modern token based authentication** , but it still requires connection to exchange online via remote powershell in order to run the legacy commands which haven't been moved over to REST. It does this however by transmitting the access token in-place of the password using a basic authentication mechanism, as remote powershell does not support native token auth.

This means that Exchange Online management using PowerShell today requires that WinRM be enabled for Basic authentication, even though when using the modern module the password is never transmitted over basic authentication.

So, unfortunately, no - today it is not possible to connect when WinRM is disabled for basic authentication. However,

- Work is being performed by the Exchange team to move the commands to REST and when that happens, the WinRM requirement can be removed.
- Whilst we require you enable WinRM Basic authentication, the password is never sent using Basic authentication (only the access token)
- You don't need basic authentication enabled service side (so that can be disabled using conditional access)

**Comment by danielmaddern** [comment]
Is there any instructions to get past the error I got with WinRM? Happy to give it a shot.
